Update comment.workflow.yml

diff --git a/.github/workflows/comment.workflow.yml b/.github/workflows/comment.workflow.yml
--- a/.github/workflows/comment.workflow.yml
+++ b/.github/workflows/comment.workflow.yml
@@ -34,8 +34,11 @@ jobs:
         if: env.VALID == 'true'
         continue-on-error: true
         run: |
+          # Replace "exit 1" with your actual command
           exit 1
-          echo "EXIT_CODE=$?" >> $GITHUB_ENV
+          # Capture the exit code in a variable
+          exit_code=$?
+          echo "EXIT_CODE=$exit_code" >> $GITHUB_ENV
       - name: exit
         run: | 
           exit ${{ env.EXIT_CODE }}
